(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_12 kitchen_18 kitchen_22_1 kitchen_22_2 kitchen_25 kitchen_28 kitchen_32 - item
  )
  (:init
    (clear kitchen_12)
    (clear kitchen_18)
    (clear kitchen_22_1)
    (clear kitchen_22_2)
    (clear kitchen_25)
    (clear kitchen_28)
    (clear kitchen_32)
    (handempty)
    (ontable kitchen_12)
    (ontable kitchen_18)
    (ontable kitchen_22_1)
    (ontable kitchen_22_2)
    (ontable kitchen_25)
    (ontable kitchen_28)
    (ontable kitchen_32)
  )
  (:goal (and
    (clear kitchen_12)
    (clear kitchen_18)
    (clear kitchen_22_1)
    (clear kitchen_22_2)
    (clear kitchen_28)
    (clear kitchen_32)
    (handempty)
    (on kitchen_28 kitchen_25)
    (ontable kitchen_12)
    (ontable kitchen_18)
    (ontable kitchen_22_1)
    (ontable kitchen_22_2)
    (ontable kitchen_25)
    (ontable kitchen_32)
  ))
)
