(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_02_1 kitchen_02_2 kitchen_05 kitchen_24 kitchen_29 kitchen_30 kitchen_31 - item
  )
  (:init
    (clear kitchen_02_1)
    (clear kitchen_02_2)
    (clear kitchen_05)
    (clear kitchen_24)
    (clear kitchen_29)
    (clear kitchen_30)
    (clear kitchen_31)
    (handempty)
    (ontable kitchen_02_1)
    (ontable kitchen_02_2)
    (ontable kitchen_05)
    (ontable kitchen_24)
    (ontable kitchen_29)
    (ontable kitchen_30)
    (ontable kitchen_31)
  )
  (:goal (and
    (clear kitchen_02_1)
    (clear kitchen_02_2)
    (clear kitchen_05)
    (clear kitchen_24)
    (clear kitchen_29)
    (clear kitchen_30)
    (clear kitchen_31)
    (handempty)
    (ontable kitchen_02_1)
    (ontable kitchen_02_2)
    (ontable kitchen_05)
    (ontable kitchen_24)
    (ontable kitchen_29)
    (ontable kitchen_30)
    (ontable kitchen_31)
  ))
)
