(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_06 kitchen_15 kitchen_26 kitchen_30 - item
  )
  (:init
    (clear kitchen_06)
    (clear kitchen_15)
    (clear kitchen_26)
    (clear kitchen_30)
    (handempty)
    (ontable kitchen_06)
    (ontable kitchen_15)
    (ontable kitchen_26)
    (ontable kitchen_30)
  )
  (:goal (and
    (clear kitchen_06)
    (clear kitchen_15)
    (clear kitchen_30)
    (handempty)
    (on kitchen_15 kitchen_26)
    (ontable kitchen_06)
    (ontable kitchen_26)
    (ontable kitchen_30)
  ))
)
