(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_04 kitchen_10 kitchen_26 kitchen_27 kitchen_28 - item
  )
  (:init
    (clear kitchen_04)
    (clear kitchen_10)
    (clear kitchen_26)
    (clear kitchen_27)
    (clear kitchen_28)
    (handempty)
    (ontable kitchen_04)
    (ontable kitchen_10)
    (ontable kitchen_26)
    (ontable kitchen_27)
    (ontable kitchen_28)
  )
  (:goal (and
    (clear kitchen_04)
    (clear kitchen_10)
    (clear kitchen_27)
    (clear kitchen_28)
    (handempty)
    (on kitchen_27 kitchen_26)
    (ontable kitchen_04)
    (ontable kitchen_10)
    (ontable kitchen_26)
    (ontable kitchen_28)
  ))
)
