(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_03 kitchen_09 kitchen_16 kitchen_18 kitchen_20 kitchen_23 - item
  )
  (:init
    (clear kitchen_03)
    (clear kitchen_09)
    (clear kitchen_16)
    (clear kitchen_18)
    (clear kitchen_20)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_03)
    (ontable kitchen_09)
    (ontable kitchen_16)
    (ontable kitchen_18)
    (ontable kitchen_20)
    (ontable kitchen_23)
  )
  (:goal (and
    (clear kitchen_03)
    (clear kitchen_09)
    (clear kitchen_16)
    (clear kitchen_18)
    (clear kitchen_20)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_03)
    (ontable kitchen_09)
    (ontable kitchen_16)
    (ontable kitchen_18)
    (ontable kitchen_20)
    (ontable kitchen_23)
  ))
)
