(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_01_1 kitchen_01_2 kitchen_12 kitchen_13 kitchen_23 - item
  )
  (:init
    (clear kitchen_01_1)
    (clear kitchen_01_2)
    (clear kitchen_12)
    (clear kitchen_13)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_01_1)
    (ontable kitchen_01_2)
    (ontable kitchen_12)
    (ontable kitchen_13)
    (ontable kitchen_23)
  )
  (:goal (and
    (clear kitchen_01_1)
    (clear kitchen_01_2)
    (clear kitchen_12)
    (clear kitchen_13)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_01_1)
    (ontable kitchen_01_2)
    (ontable kitchen_12)
    (ontable kitchen_13)
    (ontable kitchen_23)
  ))
)
