(define (problem generated)
  (:domain manip)
  (:objects
    shape_06 shape_11 shape_12_1 shape_12_2 shape_20 shape_21 - item
  )
  (:init
    (clear shape_06)
    (clear shape_11)
    (clear shape_12_1)
    (clear shape_12_2)
    (clear shape_20)
    (clear shape_21)
    (handempty)
    (ontable shape_06)
    (ontable shape_11)
    (ontable shape_12_1)
    (ontable shape_12_2)
    (ontable shape_20)
    (ontable shape_21)
  )
  (:goal (and
    (clear shape_11)
    (clear shape_12_1)
    (clear shape_12_2)
    (clear shape_20)
    (clear shape_21)
    (handempty)
    (on shape_20 shape_06)
    (ontable shape_06)
    (ontable shape_11)
    (ontable shape_12_1)
    (ontable shape_12_2)
    (ontable shape_21)
  ))
)
