(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_03 kitchen_19 kitchen_22 kitchen_23 - item
  )
  (:init
    (clear kitchen_03)
    (clear kitchen_19)
    (clear kitchen_22)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_03)
    (ontable kitchen_19)
    (ontable kitchen_22)
    (ontable kitchen_23)
  )
  (:goal (and
    (clear kitchen_03)
    (clear kitchen_19)
    (clear kitchen_22)
    (clear kitchen_23)
    (handempty)
    (ontable kitchen_03)
    (ontable kitchen_19)
    (ontable kitchen_22)
    (ontable kitchen_23)
  ))
)
