(define (problem scene1)
  (:domain manip)
  (:objects
    strawberry_1 strawberry_2 orange yellow corn can water bottle plastic knife black spoon - item
  )
  (:init
    (ontable strawberry_1)
    (ontable strawberry_2)
    (ontable orange)
    (ontable yellow corn can)
    (ontable water bottle)
    (ontable plastic knife)
    (ontable black spoon)
    (handempty)
    (clear strawberry_1)
    (clear strawberry_2)
    (clear orange)
    (clear yellow corn can)
    (clear water bottle)
    (clear plastic knife)
    (clear black spoon)
  )
  (:goal (and ))
)