(define (problem scene1)
  (:domain manip)
  (:objects
    long red block_1 long red block_2 red cylinder yellow cylinder_1 yellow cylinder_2 small blue triangular prism blue cylinder small green cube long green block large green triangular prism - obj
  )
  (:init
    (ontable long red block_1)
    (ontable long red block_2)
    (ontable red cylinder)
    (ontable yellow cylinder_1)
    (ontable yellow cylinder_2)
    (ontable small blue triangular prism)
    (ontable blue cylinder)
    (ontable small green cube)
    (ontable long green block)
    (ontable large green triangular prism)
    (clear long red block_1)
    (clear long red block_2)
    (clear red cylinder)
    (clear yellow cylinder_1)
    (clear yellow cylinder_2)
    (clear small blue triangular prism)
    (clear blue cylinder)
    (clear small green cube)
    (clear long green block)
    (clear large green triangular prism)
    (handempty)
  )
  (:goal (and ))
)