(define (problem scene1)
  (:domain manip)
  (:objects
    small yellow triangular prism_1 small yellow triangular prism_2 yellow half cylinder long blue block small blue triangular prism_1 small blue triangular prism_2 large green triangular prism_1 large green triangular prism_2 - item
    big yellow shopping basket green basket - container
  )
  (:init
    (ontable small yellow triangular prism_1)
    (ontable yellow half cylinder)
    (ontable small blue triangular prism_1)
    (ontable large green triangular prism_2)
    (on small yellow triangular prism_2 large green triangular prism_2)
    (ontable big yellow shopping basket)
    (ontable green basket)
    (in long blue block green basket)
    (in small blue triangular prism_2 green basket)
    (in large green triangular prism_1 big yellow shopping basket)
    (clear small yellow triangular prism_1)
    (clear small yellow triangular prism_2)
    (clear yellow half cylinder)
    (clear small blue triangular prism_1)
    (clear small blue triangular prism_2)
    (clear large green triangular prism_1)
    (clear large green triangular prism_2)
    (clear big yellow shopping basket)
    (clear green basket)
    (handempty)
  )
  (:goal (and ))
)