(define (problem generated)
  (:domain manip)
  (:objects
    kitchen_11 kitchen_13 kitchen_16 kitchen_24 kitchen_28 - item
  )
  (:init
    (clear kitchen_11)
    (clear kitchen_13)
    (clear kitchen_16)
    (clear kitchen_24)
    (clear kitchen_28)
    (handempty)
    (ontable kitchen_11)
    (ontable kitchen_13)
    (ontable kitchen_16)
    (ontable kitchen_24)
    (ontable kitchen_28)
  )
  (:goal (and))
)
