(define (problem generated)
  (:domain manip)
  (:objects
    office_01 office_03 office_05 office_07 office_08 office_09 - item
  )
  (:init
    (clear office_01)
    (clear office_03)
    (clear office_05)
    (clear office_07)
    (clear office_08)
    (clear office_09)
    (handempty)
    (ontable office_01)
    (ontable office_03)
    (ontable office_05)
    (ontable office_07)
    (ontable office_08)
    (ontable office_09)
  )
  (:goal (and))
)
