(define (problem generated)
  (:domain manip)
  (:objects
    shape_03 shape_07 shape_10 shape_11 shape_12 shape_14 shape_20 - item
  )
  (:init
    (clear shape_03)
    (clear shape_07)
    (clear shape_10)
    (clear shape_11)
    (clear shape_12)
    (clear shape_14)
    (clear shape_20)
    (handempty)
    (ontable shape_03)
    (ontable shape_07)
    (ontable shape_10)
    (ontable shape_11)
    (ontable shape_12)
    (ontable shape_14)
    (ontable shape_20)
  )
  (:goal (and))
)
