(define (problem generated)
  (:domain manip)
  (:objects
    shape_06 shape_07 shape_11 shape_23 shape_27 shape_28 - item
  )
  (:init
    (clear shape_06)
    (clear shape_07)
    (clear shape_11)
    (clear shape_23)
    (clear shape_27)
    (clear shape_28)
    (handempty)
    (ontable shape_06)
    (ontable shape_07)
    (ontable shape_11)
    (ontable shape_23)
    (ontable shape_27)
    (ontable shape_28)
  )
  (:goal (and))
)
