(define (problem generated)
  (:domain manip)
  (:objects
    tool_01 tool_03 tool_06 tool_07 tool_08 - item
  )
  (:init
    (clear tool_01)
    (clear tool_03)
    (clear tool_06)
    (clear tool_07)
    (clear tool_08)
    (handempty)
    (ontable tool_01)
    (ontable tool_03)
    (ontable tool_06)
    (ontable tool_07)
    (ontable tool_08)
  )
  (:goal (and))
)
