(define (problem generated)
  (:domain manip)
  (:objects
    tool_04 tool_05 tool_06 tool_07 tool_09 - item
  )
  (:init
    (clear tool_04)
    (clear tool_05)
    (clear tool_06)
    (clear tool_07)
    (clear tool_09)
    (handempty)
    (ontable tool_04)
    (ontable tool_05)
    (ontable tool_06)
    (ontable tool_07)
    (ontable tool_09)
  )
  (:goal (and))
)
