(define (problem generated)
  (:domain manip)
  (:objects
    office_04 office_05 office_07 tool_05 tool_08 - item
  )
  (:init
    (clear office_04)
    (clear office_05)
    (clear office_07)
    (clear tool_05)
    (clear tool_08)
    (handempty)
    (ontable office_04)
    (ontable office_05)
    (ontable office_07)
    (ontable tool_05)
    (ontable tool_08)
  )
  (:goal (and))
)
